# Server configs
server:
  # Server name
  name: ${BADGER_SERVER_NAME:-badger}
  # Env mode (dev or prod)
  mode: ${BADGER_SERVER_MODE:-prod}
  # HTTP port
  port: ${BADGER_SERVER_PORT:-8000}
  # Hostname
  hostname: ${BADGER_SERVER_HOSTNAME:-127.0.0.1}
  # TLS configs
  tls:
    status: ${BADGER_SERVER_TLS_STATUS:-off}
    crt_path: ${BADGER_SERVER_TLS_PEMPATH:-cert/server.crt}
    key_path: ${BADGER_SERVER_TLS_KEYPATH:-cert/server.key}

  # Global timeout
  timeout: ${BADGER_SERVER_TIMEOUT:-50}

  # Prometheus metrics endpoint
  metrics:
    username: ${BADGER_SERVER_PROM_METRICS_USERNAME:-admin}
    secret: ${BADGER_SERVER_PROM_METRICS_SECRET:-secret}

  # Log configs
  log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${BADGER_SERVER_LOG_LEVEL:-debug}
    # Output can be stdout or abs path to log file /var/logs/badger.log
    output: ${BADGER_SERVER_LOG_OUTPUT:-stdout}
    # Format can be json
    format: ${BADGER_SERVER_LOG_FORMAT:-json}
